[xdebug]
;zend_extension=xdebug.so  ;<- this is supposed to be loaded in /usr/local/etc/php/conf.d/docker-php-ext-xdebug.ini
xdebug.mode = debug
xdebug.idekey=PHPSTORM
xdebug.discover_client_host = 1
xdebug.max_nesting_level=400
xdebug.start_with_request=trigger
xdebug.client_port = 9003

; Client host is "host.docker.internal" on Mac or Windows,
; or your current machine's name on unix (type 'hostname' in a terminal)
xdebug.client_host = dev
