GRANT ALL PRIVILEGES ON *.* TO 'root'@'%' IDENTIFIED BY 'EfAwAwvQoOJB5nY61K' WITH GRANT OPTION;
GRANT ALL PRIVILEGES ON *.* TO 'objectmapper'@'%' IDENTIFIED BY 'EfAwAwvQoOJB5nY61K';
FLUSH PRIVILEGES;
